export const TEST_USER_PASSWORD = "TestOnlyPass!123";

export const TEST_USERS = [
    {
        key: "selfRegisteredCustomer",
        id: 1,
        username: "seed.customer",
        firstName: "Seed",
        lastName: "Customer",
        email: "seed.customer@test.local",
        role: "customer",
        status: "active",
        purpose: "Primary self-registered customer for happy-path login and booking tests.",
        provisionedBy: "self-registered",
        mustCompleteProfile: false,
        mustChangePassword: false,
        autoLogoutMinutes: 15,
    },
    {
        key: "admin",
        id: 2,
        username: "seed.admin",
        firstName: "Seed",
        lastName: "Admin",
        email: "seed.admin@test.local",
        role: "admin",
        status: "active",
        purpose: "Admin dashboard and customer-management test account.",
        provisionedBy: "seed-script",
        mustCompleteProfile: false,
        mustChangePassword: false,
        autoLogoutMinutes: 15,
    },
    {
        key: "root",
        id: 3,
        username: "seed.root",
        firstName: "Seed",
        lastName: "Root",
        email: "seed.root@test.local",
        role: "root",
        status: "active",
        purpose: "Root-only administrative access tests.",
        provisionedBy: "seed-script",
        mustCompleteProfile: false,
        mustChangePassword: false,
        autoLogoutMinutes: 15,
    },
    {
        key: "adminCreatedCustomer",
        id: 4,
        username: "seed.admin-created",
        firstName: "Seed",
        lastName: "Provisioned",
        email: "seed.admin-created@test.local",
        role: "customer",
        status: "pending_activation",
        purpose: "Customer created by admin with forced first-login setup requirements.",
        provisionedBy: "admin-created",
        mustCompleteProfile: true,
        mustChangePassword: true,
        autoLogoutMinutes: 15,
    },
    {
        key: "inactiveCustomer",
        id: 5,
        username: "seed.inactive",
        firstName: "Seed",
        lastName: "Inactive",
        email: "seed.inactive@test.local",
        role: "customer",
        status: "inactive",
        purpose: "Account blocked by profile-completion gate.",
        provisionedBy: "seed-script",
        mustCompleteProfile: true,
        mustChangePassword: false,
        autoLogoutMinutes: 15,
    },
    {
        key: "suspendedCustomer",
        id: 6,
        username: "seed.suspended",
        firstName: "Seed",
        lastName: "Suspended",
        email: "seed.suspended@test.local",
        role: "customer",
        status: "suspended",
        purpose: "Login lockout coverage for suspended/locked account behavior.",
        provisionedBy: "seed-script",
        mustCompleteProfile: false,
        mustChangePassword: false,
        autoLogoutMinutes: 15,
        lockout: {
            failedCount: 3,
            lockHours: 1,
        },
    },
];

export const TEST_USERS_BY_KEY = Object.fromEntries(
    TEST_USERS.map((user) => [user.key, user])
);